"""Initial schema.

One revision, because the database is created from scratch at deploy time —
there is no earlier shape to carry data across from.

Design notes:
-----
* ``question_id`` is unique across both Parts, so ``part`` lives on
  ``questions`` alone. Child tables reference the question and nothing else: a
  child row cannot disagree with its question's part because it never restates
  it, and no caller has to pass a part that only repeats what the id already
  determines.
* ``questions.answer`` is NULL when a year ships without an answer key. The
  question still loads so its image is servable, and scoring treats a NULL key
  as matching nothing (see ``core.answer.check_answer``) — no sentinel value
  has to be chosen for being unreachable.
* Question images are files, not rows. ~400MB of static images in a database
  that is otherwise a few megabytes of reference rows would ride along in every
  ``pg_dump`` and down the tunnel on every re-seed, so ``images`` stores each
  one's path and content hash and the corpus is synced to the server directly.
  The hash is not redundant with the path: re-extracting a question rewrites
  the *same* path, and the cached ``telegram_file_id`` has to be dropped when
  that happens or the bot serves the superseded upload forever. Nothing in the
  schema can enforce that a row's file exists — ``digitex-db check-images`` is
  what reconciles the two.
* ``session_answers`` snapshots ``correct_answer``. A recorded answer is
  history: correcting an answer key later must not rewrite what a student was
  told, and the stored ``is_correct`` must not drift from the key it was judged
  against. For the same reason its question reference is ON DELETE RESTRICT —
  reference data does not get to delete history.
* A UNIQUE constraint is an index, so no index is declared for a lookup some
  constraint already covers: ``UNIQUE (option_id, part, question_number)``
  serves every ``option_id``-prefixed probe, and ``session_answers``' primary
  key serves every ``session_id``-prefixed one.
* Autogenerate is disabled (no ORM models). Migrations are hand-written.

Revision ID: 0001
Revises:
Create Date: 2026-08-13
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

_TABLES = (
    """
    CREATE TABLE subjects (
        subject_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        TEXT NOT NULL UNIQUE
    )
    """,
    """
    CREATE TABLE books (
        book_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        subject_id BIGINT NOT NULL REFERENCES subjects(subject_id)
                                   ON DELETE CASCADE,
        year_value INTEGER NOT NULL,
        UNIQUE (subject_id, year_value)
    )
    """,
    """
    CREATE TABLE options (
        option_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        book_id       BIGINT NOT NULL REFERENCES books(book_id)
                                      ON DELETE CASCADE,
        option_number INTEGER NOT NULL
                      CHECK (option_number BETWEEN 1 AND 10),
        exam_type     TEXT NOT NULL DEFAULT 'CT'
                      CHECK (exam_type IN ('CE', 'CT')),
        UNIQUE (book_id, option_number)
    )
    """,
    # A NULL answer means "no answer key for this question" — see the module
    # docstring. The Part A pattern therefore excludes 0 and leading zeros:
    # an answer is a positive option index, and "no key" is spelled NULL.
    """
    CREATE TABLE questions (
        question_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        option_id       BIGINT NOT NULL REFERENCES options(option_id)
                                        ON DELETE CASCADE,
        part            TEXT NOT NULL CHECK (part IN ('A', 'B')),
        question_number INTEGER NOT NULL CHECK (question_number > 0),
        answer          TEXT,
        CONSTRAINT part_a_answer_is_an_option_index
            CHECK (part <> 'A' OR answer IS NULL OR answer ~ '^[1-9][0-9]*$'),
        UNIQUE (option_id, part, question_number)
    )
    """,
    # One image per question, so the question id is the key. The image itself
    # is a file — see the module docstring — so the row carries where it is and
    # what is in it; ``telegram_file_id`` is a cache the bot fills on the first
    # upload.
    #
    # ``object_key`` is UNIQUE because it is derived from the question's natural
    # key: two questions naming one file means the key was built wrong, and a
    # constraint says so at seed time rather than by serving the wrong image
    # later.
    """
    CREATE TABLE images (
        question_id      BIGINT PRIMARY KEY REFERENCES questions(question_id)
                                            ON DELETE CASCADE,
        object_key       TEXT NOT NULL UNIQUE,
        content_hash     TEXT NOT NULL,
        telegram_file_id TEXT
    )
    """,
    # Topics are named once and referenced by id, so a rename is one UPDATE and
    # a typo cannot quietly become a second topic. A topic belongs to a subject:
    # two subjects may both have "Оптика" without sharing questions.
    """
    CREATE TABLE topics (
        topic_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        subject_id BIGINT NOT NULL REFERENCES subjects(subject_id)
                                   ON DELETE CASCADE,
        name       TEXT NOT NULL,
        UNIQUE (subject_id, name)
    )
    """,
    """
    CREATE TABLE question_topics (
        question_id BIGINT NOT NULL REFERENCES questions(question_id)
                                    ON DELETE CASCADE,
        topic_id    BIGINT NOT NULL REFERENCES topics(topic_id)
                                    ON DELETE CASCADE,
        PRIMARY KEY (question_id, topic_id)
    )
    """,
    # One row per person, keyed by the id Telegram assigns them. The
    # registration workflow lives here rather than in a second table keyed by
    # the same id: every student has exactly one status, and the authorization
    # check on every callback is then a single primary-key lookup.
    #
    # ``telegram_name`` is the display name Telegram reports, refreshed on each
    # /start. ``full_name`` is what the student typed when applying, so it is
    # NULL until they do.
    """
    CREATE TABLE students (
        telegram_id       BIGINT PRIMARY KEY,
        telegram_name     TEXT NOT NULL,
        telegram_username TEXT,
        full_name         TEXT,
        status            TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'approved', 'rejected')),
        created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        handled_at        TIMESTAMPTZ,
        handled_by        BIGINT REFERENCES students(telegram_id)
                                 ON DELETE SET NULL,
        CONSTRAINT decision_is_recorded_with_its_status
            CHECK ((status = 'pending') = (handled_at IS NULL)),
        CONSTRAINT decision_implies_an_application
            CHECK (status = 'pending' OR full_name IS NOT NULL)
    )
    """,
    # ON DELETE RESTRICT on the option: a session is history, and reference data
    # does not get to delete it. Deleting the student does, though — that is a
    # person asking to be forgotten, not a corpus edit.
    """
    CREATE TABLE test_sessions (
        session_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_telegram_id BIGINT NOT NULL REFERENCES students(telegram_id)
                                            ON DELETE CASCADE,
        option_id           BIGINT NOT NULL REFERENCES options(option_id)
                                            ON DELETE RESTRICT,
        started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        completed_at        TIMESTAMPTZ,
        CONSTRAINT completed_after_started
            CHECK (completed_at IS NULL OR completed_at >= started_at)
    )
    """,
    # ``correct_answer`` is the key as it stood when the answer was judged; it
    # is NULL when the question had no key at all. See the module docstring.
    """
    CREATE TABLE session_answers (
        session_id         BIGINT NOT NULL REFERENCES test_sessions(session_id)
                                           ON DELETE CASCADE,
        question_id        BIGINT NOT NULL REFERENCES questions(question_id)
                                           ON DELETE RESTRICT,
        student_answer     TEXT NOT NULL,
        correct_answer     TEXT,
        is_correct         BOOLEAN NOT NULL,
        time_spent_seconds DOUBLE PRECISION NOT NULL
                           CHECK (time_spent_seconds >= 0),
        answered_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (session_id, question_id)
    )
    """,
)

_INDEXES = (
    # question_topics' primary key leads with question_id, so drawing a random
    # question for a topic has no index to stand on without this one.
    "CREATE INDEX idx_question_topics_topic ON question_topics(topic_id)",
    # Serves the cascade when a student is deleted.
    "CREATE INDEX idx_test_sessions_student ON test_sessions(student_telegram_id)",
)


def upgrade() -> None:
    for statement in (*_TABLES, *_INDEXES):
        op.execute(statement)


def downgrade() -> None:
    for table in (
        "session_answers",
        "test_sessions",
        "students",
        "question_topics",
        "topics",
        "images",
        "questions",
        "options",
        "books",
        "subjects",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
