[project]
name = "digitex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "doxapy>=0.9.2",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "paddleocr>=2.10.0",
    "paddlepaddle-gpu>=2.6.2",
    "pydantic-settings>=2.8.1",
    "pypdfium2>=4.30.1",
    "setuptools>=78.1.0",
]
