[project]
name = "digitex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.5",
    "doxapy>=0.9.2",
    "lmdb>=1.6.2",
    "numpy>=2.2.4",
    "onnxruntime>=1.21.0",
    "opencv-python>=4.11.0.86",
    "opencv-python-headless>=4.11.0.86",
    "pyclipper>=1.3.0.post6",
    "pydantic-settings>=2.8.1",
    "pypdfium2>=4.30.1",
    "python-doctr>=0.11.0",
    "pyyaml>=6.0.2",
    "rapidfuzz>=3.13.0",
    "setuptools>=78.1.0",
    "supervision>=0.25.1",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.23",
]
