[project]
name = "modules"
version = "0.1.0"
description = "Helper classes for data processing"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.setuptools]
py-modules = []