"""Initial schema.

Translation of the former ``scripts/script.sql`` (SQLite) into PostgreSQL.

Notes:
-----
* Primary keys use ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` so that the
  one-shot data migration (``scripts/migrate_sqlite_to_postgres.py``) can insert
  the existing SQLite ids with ``OVERRIDING SYSTEM VALUE``.
* ``images.question_id`` and ``question_topics.question_id`` and
  ``session_answers.question_id`` reference *either* ``part_a_questions`` or
  ``part_b_questions``. A single FK cannot express a dual-parent reference;
  this is the structural cost of keeping the Part A / Part B tables split.
  Application-level invariants enforce referential integrity instead.
* Autogenerate is disabled (no ORM models). Migrations are hand-written.

Revision ID: 0001
Revises:
Create Date: 2026-05-21
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE subjects (
            subject_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL UNIQUE
        )
        """
    )

    op.execute(
        """
        CREATE TABLE books (
            book_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            subject_id    BIGINT NOT NULL REFERENCES subjects(subject_id),
            year_value    INTEGER NOT NULL,
            a_num_options INTEGER NOT NULL DEFAULT 5,
            UNIQUE (subject_id, year_value)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE options (
            option_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id       BIGINT NOT NULL REFERENCES books(book_id),
            option_number INTEGER NOT NULL
                          CHECK (option_number BETWEEN 1 AND 10),
            exam_type     TEXT NOT NULL DEFAULT 'CT'
                          CHECK (exam_type IN ('CE', 'CT')),
            UNIQUE (book_id, option_number)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE part_a_questions (
            question_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            option_id       BIGINT NOT NULL REFERENCES options(option_id),
            question_number INTEGER NOT NULL,
            answer          INTEGER NOT NULL CHECK (answer BETWEEN 1 AND 5),
            UNIQUE (option_id, question_number)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE part_b_questions (
            question_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            option_id       BIGINT NOT NULL REFERENCES options(option_id),
            question_number INTEGER NOT NULL,
            answer          TEXT NOT NULL,
            UNIQUE (option_id, question_number)
        )
        """
    )

    # No FK on question_id: it points to either part_a_questions or part_b_questions.
    op.execute(
        """
        CREATE TABLE images (
            image_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id       BIGINT NOT NULL,
            part              TEXT NOT NULL CHECK (part IN ('A', 'B')),
            image_data        BYTEA NOT NULL,
            telegram_file_id  TEXT,
            UNIQUE (question_id, part)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE students (
            student_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            telegram_id BIGINT NOT NULL UNIQUE,
            name        TEXT NOT NULL,
            username    TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE test_sessions (
            session_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_id   BIGINT NOT NULL REFERENCES students(student_id),
            option_id    BIGINT NOT NULL REFERENCES options(option_id),
            started_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            completed_at TIMESTAMPTZ
        )
        """
    )

    # No FK on question_id (dual parent — see module docstring).
    op.execute(
        """
        CREATE TABLE question_topics (
            question_id BIGINT NOT NULL,
            part        TEXT NOT NULL CHECK (part IN ('A', 'B')),
            topic_name  TEXT NOT NULL,
            PRIMARY KEY (question_id, part, topic_name)
        )
        """
    )

    # No FK on question_id (dual parent — see module docstring).
    op.execute(
        """
        CREATE TABLE session_answers (
            answer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id     BIGINT NOT NULL REFERENCES test_sessions(session_id)
                                                  ON DELETE CASCADE,
            question_id    BIGINT NOT NULL,
            student_answer TEXT NOT NULL,
            is_correct     BOOLEAN NOT NULL,
            time_spent     DOUBLE PRECISION NOT NULL,
            answered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (session_id, question_id)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE authorized_users (
            telegram_id       BIGINT PRIMARY KEY,
            full_name         TEXT NOT NULL,
            telegram_username TEXT,
            status            TEXT NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending', 'approved', 'rejected')),
            created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            handled_at        TIMESTAMPTZ,
            handled_by        BIGINT
        )
        """
    )

    op.execute("CREATE INDEX idx_books_subject_year ON books(subject_id, year_value)")
    op.execute("CREATE INDEX idx_options_book_exam ON options(book_id, exam_type)")
    op.execute("CREATE INDEX idx_options_exam_type ON options(exam_type)")
    op.execute("CREATE INDEX idx_question_topics_topic ON question_topics(topic_name)")
    op.execute(
        "CREATE INDEX idx_session_answers_session ON session_answers(session_id)"
    )
    op.execute(
        "CREATE INDEX idx_session_answers_correct"
        " ON session_answers(session_id, is_correct)"
    )


def downgrade() -> None:
    for table in (
        "authorized_users",
        "session_answers",
        "question_topics",
        "test_sessions",
        "students",
        "images",
        "part_b_questions",
        "part_a_questions",
        "options",
        "books",
        "subjects",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
