"""Merge part_a_questions / part_b_questions into one questions table.

Why
---
Two near-identical tables meant every question query either picked a table by
part or ran twice and UNION-ALLed the halves, which grew a SQL-templating layer
in ``repositories/_common.py``. It also cost real data: the two tables had
separate identity sequences, so both held a ``question_id`` 1, and migration
0002 exists solely to widen ``session_answers``' key after Part Б answers were
silently discarded by ``ON CONFLICT DO NOTHING``.

One table with a ``part`` column makes the part a bound parameter, so the
templating deletes and the id-collision class of bug becomes unrepresentable.

Notes:
-----
* ``answer`` is TEXT for both parts. Part A keeps a digits-only CHECK rather
  than the old ``BETWEEN 1 AND 5``: ``scripts/populate_db.py`` stores ``'0'``
  as a deliberately unmatchable placeholder when a year has no answer key, and
  the narrower constraint rejected it — rolling back the whole year's load.
* The new table's identity starts above every old id, so remapping the child
  tables cannot transiently collide with an id still in use.
* ``images``, ``question_topics`` and ``session_answers`` gain the foreign keys
  a dual-parent reference could not express. They keep their ``part`` column,
  now referencing ``questions (question_id, part)`` — so a child row's part can
  no longer disagree with its question's.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-12
"""

from __future__ import annotations

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE questions (
            question_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            option_id       BIGINT NOT NULL REFERENCES options(option_id),
            part            TEXT NOT NULL CHECK (part IN ('A', 'B')),
            question_number INTEGER NOT NULL,
            answer          TEXT NOT NULL,
            CONSTRAINT part_a_answer_is_numeric
                CHECK (part <> 'A' OR answer ~ '^[0-9]+$'),
            UNIQUE (option_id, part, question_number),
            UNIQUE (question_id, part)
        )
        """
    )

    # Start above every existing id so the UPDATEs below can never assign a
    # new id that another not-yet-remapped child row still points at.
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('questions', 'question_id'),
            GREATEST(
                (SELECT COALESCE(MAX(question_id), 0) FROM part_a_questions),
                (SELECT COALESCE(MAX(question_id), 0) FROM part_b_questions)
            ) + 1,
            false
        )
        """
    )

    op.execute(
        """
        INSERT INTO questions (option_id, part, question_number, answer)
        SELECT option_id, 'A', question_number, answer::text
          FROM part_a_questions
        """
    )
    op.execute(
        """
        INSERT INTO questions (option_id, part, question_number, answer)
        SELECT option_id, 'B', question_number, answer
          FROM part_b_questions
        """
    )

    # (option_id, part, question_number) is unique in both the old and the new
    # shape, so it identifies each row across the move.
    op.execute(
        """
        CREATE TEMP TABLE question_id_map AS
        SELECT 'A'::text AS part, old.question_id AS old_id, new.question_id AS new_id
          FROM part_a_questions old
          JOIN questions new
            ON new.option_id = old.option_id
           AND new.part = 'A'
           AND new.question_number = old.question_number
        UNION ALL
        SELECT 'B'::text, old.question_id, new.question_id
          FROM part_b_questions old
          JOIN questions new
            ON new.option_id = old.option_id
           AND new.part = 'B'
           AND new.question_number = old.question_number
        """
    )

    for table in ("images", "question_topics", "session_answers"):
        op.execute(
            f"""
            UPDATE {table} child
               SET question_id = m.new_id
              FROM question_id_map m
             WHERE m.part = child.part
               AND m.old_id = child.question_id
            """
        )

    op.execute("DROP TABLE question_id_map")
    op.execute("DROP TABLE part_a_questions")
    op.execute("DROP TABLE part_b_questions")

    # The referential integrity the split could not express.
    for table in ("images", "question_topics", "session_answers"):
        op.execute(
            f"ALTER TABLE {table}"
            f" ADD CONSTRAINT {table}_question_fkey"
            " FOREIGN KEY (question_id, part)"
            " REFERENCES questions (question_id, part) ON DELETE CASCADE"
        )

    op.execute(
        "CREATE INDEX idx_questions_option_part"
        " ON questions(option_id, part, question_number)"
    )


def downgrade() -> None:
    """Split the table back apart.

    Part A answers are re-narrowed to INTEGER, so a placeholder ``'0'`` written
    under the merged schema fails the old ``BETWEEN 1 AND 5`` check. Such rows
    are dropped rather than blocking the downgrade — they carry no answer key.
    """
    for table in ("images", "question_topics", "session_answers"):
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {table}_question_fkey")

    op.execute(
        "DELETE FROM questions"
        " WHERE part = 'A' AND answer NOT IN ('1', '2', '3', '4', '5')"
    )

    op.execute(
        """
        CREATE TABLE part_a_questions (
            question_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            option_id       BIGINT NOT NULL REFERENCES options(option_id),
            question_number INTEGER NOT NULL,
            answer          INTEGER NOT NULL CHECK (answer BETWEEN 1 AND 5),
            UNIQUE (option_id, question_number)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE part_b_questions (
            question_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            option_id       BIGINT NOT NULL REFERENCES options(option_id),
            question_number INTEGER NOT NULL,
            answer          TEXT NOT NULL,
            UNIQUE (option_id, question_number)
        )
        """
    )

    # Ids are preserved, so the child tables need no remapping on the way back.
    op.execute(
        """
        INSERT INTO part_a_questions (question_id, option_id, question_number, answer)
        OVERRIDING SYSTEM VALUE
        SELECT question_id, option_id, question_number, answer::integer
          FROM questions WHERE part = 'A'
        """
    )
    op.execute(
        """
        INSERT INTO part_b_questions (question_id, option_id, question_number, answer)
        OVERRIDING SYSTEM VALUE
        SELECT question_id, option_id, question_number, answer
          FROM questions WHERE part = 'B'
        """
    )
    op.execute("DROP TABLE questions")
